"""
Asset loader — serves pre-generated PNG sprites/textures from assets/.

Key feature: compose_player(player, direction) builds a layered character
sprite by compositing DCSS body/head/weapon/shield/boots/gloves overlays
on top of the base figure, cached by equipment fingerprint + direction.
Falls back silently to the plain base sprite when overlays are absent.

Usage:
    from src.assets import assets
    spr = assets.compose_player(player, "south")  # layered, equipment-aware
    spr = assets.enemy("goblin")
    tex = assets.tile("floor", "dungeon", variant=0)
    spr = assets.item_sprite("Broad Sword")
"""
from __future__ import annotations

import io
import sys
from pathlib import Path

import pygame

if getattr(sys, "frozen", False):
    _ASSETS = Path(sys._MEIPASS) / "assets"   # type: ignore[attr-defined]
else:
    _ASSETS = Path(__file__).resolve().parent.parent / "assets"

_OVERLAYS = _ASSETS / "player_overlays"


# ── Equipment → overlay key mapping ──────────────────────────────────────────
# Keys match filenames under assets/player_overlays/*.png (without .png).
# Generated by tools/install_crawl_assets.py.

_CHEST_OVERLAY = {
    None:            "body_none",
    "Leather Armor": "body_Leather Armor",
    "Ring Mail":     "body_Ring Mail",
    "Chain Mail":    "body_Chain Mail",
    "Banded Mail":   "body_Banded Mail",
    "Plate Armor":   "body_Plate Armor",
    "Crystal Plate": "body_Crystal Plate",
}

_HELM_OVERLAY = {
    "Cap":          "head_Cap",
    "Leather Helm": "head_Leather Helm",
    "Helm":         "head_Helm",
    "Visored Helm": "head_Visored Helm",
    "Great Helm":   "head_Great Helm",
    "Dragon Helm":  "head_Dragon Helm",
}

_WEAPON_OVERLAY = {
    "Dagger":            "wpn_Dagger",
    "Short Sword":       "wpn_Short Sword",
    "Long Sword":        "wpn_Long Sword",
    "Scimitar":          "wpn_Scimitar",
    "Rapier":            "wpn_Rapier",
    "Broad Sword":       "wpn_Broad Sword",
    "Claymore":          "wpn_Claymore",
    "Great Sword":       "wpn_Great Sword",
    "Demon Blade":       "wpn_Demon Blade",
    "Hand Axe":          "wpn_Hand Axe",
    "War Axe":           "wpn_War Axe",
    "Battle Axe":        "wpn_Battle Axe",
    "Great Axe":         "wpn_Great Axe",
    "Executioner's Axe": "wpn_Executioner's Axe",
    "Club":              "wpn_Club",
    "Mace":              "wpn_Mace",
    "Flail":             "wpn_Flail",
    "Morningstar":       "wpn_Morningstar",
    "War Hammer":        "wpn_War Hammer",
    "Dire Flail":        "wpn_Dire Flail",
    "Spear":             "wpn_Spear",
    "Halberd":           "wpn_Halberd",
    "Glaive":            "wpn_Glaive",
    "Bardiche":          "wpn_Bardiche",
    "Quarterstaff":      "wpn_Quarterstaff",
    "Battle Staff":      "wpn_Battle Staff",
    "Short Bow":         "wpn_Short Bow",
    "Long Bow":          "wpn_Long Bow",
    "Hunter's Bow":      "wpn_Hunter's Bow",
    "War Bow":           "wpn_War Bow",
    "Hand Crossbow":     "wpn_Hand Crossbow",
    "Crossbow":          "wpn_Crossbow",
    "Arbalest":          "wpn_Arbalest",
}

_SHIELD_OVERLAY = {
    "Buckler":       "shld_Buckler",
    "Heater Shield": "shld_Heater Shield",
    "Kite Shield":   "shld_Kite Shield",
    "Round Shield":  "shld_Round Shield",
    "Tower Shield":  "shld_Tower Shield",
    "Dwarven Shield":"shld_Dwarven Shield",
}

_BOOTS_OVERLAY = {
    "Leather Boots": "boot_Leather Boots",
    "Chain Boots":   "boot_Chain Boots",
    "Greaves":       "boot_Greaves",
    "Iron Boots":    "boot_Iron Boots",
}

_GLOVES_OVERLAY = {
    "Leather Gloves": "glv_Leather Gloves",
    "Chain Gloves":   "glv_Chain Gloves",
    "Gauntlets":      "glv_Gauntlets",
    "War Gauntlets":  "glv_War Gauntlets",
}


class AssetManager:
    def __init__(self):
        self._cache: dict[str, pygame.Surface | None] = {}
        self._composed_cache: dict[tuple, pygame.Surface | None] = {}

    def _load(self, path: Path, size: tuple | None = None) -> pygame.Surface | None:
        key = str(path) + str(size)
        if key in self._cache:
            return self._cache[key]
        if not path.exists():
            self._cache[key] = None
            return None
        try:
            surf = pygame.image.load(str(path)).convert_alpha()
            if size:
                surf = pygame.transform.smoothscale(surf, size)
            self._cache[key] = surf
            return surf
        except Exception:
            self._cache[key] = None
            return None

    def _load_pil(self, path: Path):
        """Load a 32×32 RGBA PIL Image, or None if unavailable."""
        if not path.exists():
            return None
        try:
            from PIL import Image
            return Image.open(str(path)).convert("RGBA")
        except Exception:
            return None

    # ── Player sprites (composited) ───────────────────────────────────────────

    def compose_player(self, player, direction: str = "south",
                        size: tuple | None = None) -> pygame.Surface | None:
        """
        Build a layered character sprite reflecting the player's equipped gear.

        Layers (bottom→top):
          1. Base body  (human_male.png, direction-flipped for east)
          2. Chest armour overlay
          3. Helm overlay
          4. Boots overlay
          5. Gloves overlay
          6. Shield overlay (hand_left)
          7. Weapon overlay (hand_right)

        Result is cached per (direction, equipment fingerprint).
        Falls back to plain base sprite if overlays are missing.
        """
        fp    = self._equip_fingerprint(player, direction)
        cached = self._composed_cache.get(fp)
        if cached is not None or fp in self._composed_cache:
            # Scale on the way out
            if cached is None:
                return self.player(direction, size)
            if size:
                return pygame.transform.smoothscale(cached, size)
            return cached

        result = self._build_composite(player, direction)
        self._composed_cache[fp] = result   # None means "use base"
        if result is None:
            return self.player(direction, size)
        if size:
            return pygame.transform.smoothscale(result, size)
        return result

    def invalidate_player_cache(self):
        """Call when equipment changes so the composite is rebuilt."""
        self._composed_cache.clear()

    def _equip_fingerprint(self, player, direction: str) -> tuple:
        eq = player.equipment
        def _bn(slot):
            item = eq.get(slot)
            return item.base_name if item is not None else None
        return (
            direction,
            _bn("chest"), _bn("helm"), _bn("weapon"),
            _bn("shield"), _bn("boots"), _bn("gloves"),
        )

    def _build_composite(self, player, direction: str):
        """Composite all overlay layers and return a 32×32 pygame.Surface, or None."""
        # Load base (32×32 RGBA PIL image)
        base_path = _ASSETS / "sprites" / "player_south.png"
        base = self._load_pil(base_path)
        if base is None:
            return None

        eq = player.equipment

        def overlay_key(item, mapping):
            if item is None:
                return None
            return mapping.get(item.base_name)

        # Gather overlay keys in draw order
        layers = []
        # Chest (always add default body overlay)
        chest_item = eq.get("chest")
        chest_key  = _CHEST_OVERLAY.get(
            chest_item.base_name if chest_item else None,
            "body_none")
        layers.append(chest_key)
        # Helm
        helm_k = overlay_key(eq.get("helm"), _HELM_OVERLAY)
        if helm_k:
            layers.append(helm_k)
        # Boots
        boot_k = overlay_key(eq.get("boots"), _BOOTS_OVERLAY)
        if boot_k:
            layers.append(boot_k)
        # Gloves
        glv_k = overlay_key(eq.get("gloves"), _GLOVES_OVERLAY)
        if glv_k:
            layers.append(glv_k)
        # Shield (only when not holding a bow)
        from src.items.item import BOW_BASES
        wpn_item  = eq.get("weapon")
        is_bow    = (wpn_item is not None and wpn_item.base_name in BOW_BASES)
        shld_item = eq.get("shield")
        if shld_item and not is_bow:
            shld_k = _SHIELD_OVERLAY.get(shld_item.base_name)
            if shld_k:
                layers.append(shld_k)
        # Weapon
        wpn_k = overlay_key(wpn_item, _WEAPON_OVERLAY)
        if wpn_k:
            layers.append(wpn_k)

        # Check if any overlay actually exists — if none do, skip compositing
        any_hit = False
        for k in layers:
            if (_OVERLAYS / f"{k}.png").exists():
                any_hit = True
                break
        if not any_hit:
            return None

        # Composite using PIL
        from PIL import Image
        result = base.copy()
        for key in layers:
            ovl = self._load_pil(_OVERLAYS / f"{key}.png")
            if ovl:
                result.paste(ovl, (0, 0), ovl)   # alpha composite

        # Apply direction transform
        if direction == "east":
            result = result.transpose(Image.FLIP_LEFT_RIGHT)
        elif direction == "north":
            pass   # same as south for top-down (player looks same from above)
        # south / west: use as-is (west will flip at caller side if needed)

        # Convert PIL → pygame
        buf = io.BytesIO()
        result.save(buf, format="PNG")
        buf.seek(0)
        return pygame.image.load(buf).convert_alpha()

    # ── Plain base player sprites ──────────────────────────────────────────────

    def player(self, direction: str = "south",
               size: tuple | None = None) -> pygame.Surface | None:
        path = _ASSETS / "sprites" / f"player_{direction}.png"
        return self._load(path, size)

    # ── Enemy sprites ─────────────────────────────────────────────────────────

    def enemy(self, kind: str, size: tuple | None = None) -> pygame.Surface | None:
        path = _ASSETS / "sprites" / "enemies" / f"{kind.lower()}.png"
        return self._load(path, size)

    # ── Tile textures ─────────────────────────────────────────────────────────

    def tile(self, tile_type: str, theme: str,
             variant: int = 0) -> pygame.Surface | None:
        path = _ASSETS / "tiles" / f"{tile_type}_{theme}_{variant % 4}.png"
        return self._load(path, (40, 40))

    # ── Town facades ──────────────────────────────────────────────────────────

    def town_facade(self, specialty: str,
                    size: tuple | None = None) -> pygame.Surface | None:
        path = _ASSETS / "town" / f"facade_{specialty}.png"
        return self._load(path, size)

    # ── Item sprites ──────────────────────────────────────────────────────────

    def item(self, kind: str,
             size: tuple | None = None) -> pygame.Surface | None:
        path = _ASSETS / "items" / f"{kind}.png"
        return self._load(path, size)

    def item_sprite(self, base_name: str,
                    size: tuple | None = None) -> pygame.Surface | None:
        return self.item(base_name, size)

    def portrait(self, race: str, gender: str,
                 size: tuple = (160, 240)) -> pygame.Surface | None:
        """Load a DCSS base portrait for the character creation screen."""
        path = (_ASSETS / "Dungeon Crawl Stone Soup Full" /
                "player" / "base" / f"{race}_{gender}.png")
        return self._load(path, size)

    def clear_cache(self):
        self._cache.clear()
        self._composed_cache.clear()

    @property
    def available(self) -> bool:
        return (_ASSETS / "sprites" / "player_south.png").exists()


# Module-level singleton
assets = AssetManager()
